// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GenerateFollowupSuggestionsRequest {
    /** Context the suggestions are generated from. */
    context?: Record<string, unknown>;
    created_by?: string;
}
