// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         runtime_version: "runtime_version"
 *     }
 */
export interface ListMessagesRequest {
    /** Runtime generation the thread lives on: '1' (the default) reads a thread of an agent on the v1 runtime; any other value (e.g. '2' or '0.5.4') reads a runtime-v2 thread. */
    runtime_version?: string;
}
