// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         interaction_id: "interaction_id",
 *         text: "text"
 *     }
 */
export interface RerunMessageRequest {
    interaction_id: string;
    text: string;
    /** End user to attribute the rerun to; omitted, the thread's original user is kept. */
    user_id?: string;
    /** Signed image URL on the replayed message. */
    image_url?: string;
    version_id?: string;
    version_tag?: string;
    /** Optional runtime build pin (e.g. '0.5.4') for agents on the runtime-v2 engine. Has no effect on which engine serves the agent; omit to use the current default runtime. */
    runtime_version?: string;
}
