// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         accept: "accept",
 *         "Last-Event-ID": "Last-Event-ID",
 *         agent_id: "agent_id",
 *         text: "text",
 *         user_id: "user_id"
 *     }
 */
export interface SendMessageRequest {
    accept?: string;
    "Last-Event-ID"?: string;
    agent_id: string;
    text: string;
    user_id: string;
    thread_id?: string;
    /** Signed image URL for vision input; forwarded to IA as body.image.signed_url. */
    image_url?: string;
}
