// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         "Last-Event-ID": "Last-Event-ID",
 *         body: {
 *             text: "text",
 *             user_id: "user_id"
 *         }
 *     }
 */
export interface StreamMessageRequest {
    "Last-Event-ID"?: string;
    body: Apollo.SendMessageRequest;
}
