// This file was auto-generated by Fern from our API Definition.

export const ThreadTraceRequestSortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ThreadTraceRequestSortOrder =
    (typeof ThreadTraceRequestSortOrder)[keyof typeof ThreadTraceRequestSortOrder];
