// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface WebhookEvent {
    /** The message to run the agent on. When omitted, the agent runs on agent_variables alone. */
    text?: string;
    /** Free-form key/value data passed to the agent as variables for this event. */
    agent_variables?: Record<string, unknown>;
    /** Your own id for the conversation this event belongs to. Reuse the same value to continue a conversation; omit it to start a new one. Unique per agent. */
    thread_id?: string;
}
