// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace Agents {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Agents {
    protected readonly _options: Agents.Options;

    constructor(_options: Agents.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {string} projectId
     * @param {Apollo.ListAgentsRequest} request
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.listAgents("projectId", {
     *         filters: {}
     *     })
     */
    public listAgents(
        projectId: string,
        request: Apollo.ListAgentsRequest,
        requestOptions?: Agents.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ExternalPageExternalAgent> {
        return core.HttpResponsePromise.fromPromise(this.__listAgents(projectId, request, requestOptions));
    }

    private async __listAgents(
        projectId: string,
        request: Apollo.ListAgentsRequest,
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ExternalPageExternalAgent>> {
        const {
            filters,
            "page[size]": pageSize,
            "page[after]": pageAfter,
            "page[before]": pageBefore,
            sort_by: sortBy,
            sort_order: sortOrder,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.filters = filters;
        if (pageSize != null) {
            _queryParams["page[size]"] = pageSize.toString();
        }

        if (pageAfter != null) {
            _queryParams["page[after]"] = pageAfter;
        }

        if (pageBefore != null) {
            _queryParams["page[before]"] = pageBefore;
        }

        if (sortBy != null) {
            _queryParams.sort_by = sortBy;
        }

        if (sortOrder != null) {
            _queryParams.sort_order = sortOrder;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/projects/${core.url.encodePathParam(projectId)}/agents`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ExternalPageExternalAgent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /management/v1/projects/{projectId}/agents.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} projectId
     * @param {Apollo.ExternalAgentCreateRequest} request
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.createAgent("projectId", {
     *         name: "name"
     *     })
     */
    public createAgent(
        projectId: string,
        request: Apollo.ExternalAgentCreateRequest,
        requestOptions?: Agents.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ExternalAgentCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAgent(projectId, request, requestOptions));
    }

    private async __createAgent(
        projectId: string,
        request: Apollo.ExternalAgentCreateRequest,
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ExternalAgentCreateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/projects/${core.url.encodePathParam(projectId)}/agents`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ExternalAgentCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /management/v1/projects/{projectId}/agents.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.getAgent("agentId")
     */
    public getAgent(
        agentId: string,
        requestOptions?: Agents.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ExternalAgent> {
        return core.HttpResponsePromise.fromPromise(this.__getAgent(agentId, requestOptions));
    }

    private async __getAgent(
        agentId: string,
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ExternalAgent>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ExternalAgent, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /management/v1/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.deleteAgent("agentId")
     */
    public deleteAgent(agentId: string, requestOptions?: Agents.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAgent(agentId, requestOptions));
    }

    private async __deleteAgent(
        agentId: string,
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling DELETE /management/v1/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {Apollo.ExternalAgentUpdateRequest} request
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.updateAgent("agentId")
     */
    public updateAgent(
        agentId: string,
        request: Apollo.ExternalAgentUpdateRequest = {},
        requestOptions?: Agents.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ExternalAgentUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAgent(agentId, request, requestOptions));
    }

    private async __updateAgent(
        agentId: string,
        request: Apollo.ExternalAgentUpdateRequest = {},
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ExternalAgentUpdateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ExternalAgentUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling PATCH /management/v1/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {Apollo.GetAgentUsageRequest} request
     * @param {Agents.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agents.getAgentUsage("agentId", {
     *         created_from: "2024-01-15T09:30:00Z",
     *         created_to: "2024-01-15T09:30:00Z"
     *     })
     */
    public getAgentUsage(
        agentId: string,
        request: Apollo.GetAgentUsageRequest = {},
        requestOptions?: Agents.RequestOptions,
    ): core.HttpResponsePromise<Apollo.UsageResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAgentUsage(agentId, request, requestOptions));
    }

    private async __getAgentUsage(
        agentId: string,
        request: Apollo.GetAgentUsageRequest = {},
        requestOptions?: Agents.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.UsageResponse>> {
        const { created_from: createdFrom, created_to: createdTo } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (createdFrom != null) {
            _queryParams.created_from = createdFrom;
        }

        if (createdTo != null) {
            _queryParams.created_to = createdTo;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.UsageResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /management/v1/agents/{agentId}/usage.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
