// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace Messaging {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Messaging {
    protected readonly _options: Messaging.Options;

    constructor(_options: Messaging.Options = {}) {
        this._options = _options;
    }

    /**
     * Send a message; auto-create the thread when ``thread_id`` is omitted. For a live
     * token stream use ``POST /messages/stream`` (SSE). The resolved thread id is
     * returned in the body.
     *
     * @param {Apollo.SendMessageRequest} request
     * @param {Messaging.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.messaging.sendMessage({
     *         agent_id: "agent_id",
     *         text: "text",
     *         user_id: "user_id"
     *     })
     */
    public sendMessage(
        request: Apollo.SendMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<Apollo.SendMessageResponse> {
        return core.HttpResponsePromise.fromPromise(this.__sendMessage(request, requestOptions));
    }

    private async __sendMessage(
        request: Apollo.SendMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.SendMessageResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "messaging/v1/messages",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.SendMessageResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /messaging/v1/messages.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Send a message and stream tokens over Server-Sent Events. Auto-creates the
     * thread when ``thread_id`` is omitted — the resolved id arrives as the first
     * ``thread`` event (an SSE client can't read response headers). Resume a dropped
     * stream with the standard ``Last-Event-ID`` header: buffered frames replay, no
     * fresh turn. FastAPI owns the wire format, keep-alive pings, and OpenAPI docs.
     */
    public streamMessage(
        request: Apollo.StreamMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<Apollo.StreamMessageResponse>> {
        return core.HttpResponsePromise.fromPromise(this.__streamMessage(request, requestOptions));
    }

    private async __streamMessage(
        request: Apollo.StreamMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<Apollo.StreamMessageResponse>>> {
        const { "Last-Event-ID": lastEventId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "Last-Event-ID": lastEventId != null ? lastEventId : undefined }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher<ReadableStream>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "messaging/v1/messages/stream",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: new core.Stream({
                    stream: _response.body,
                    parse: (data) => data as any,
                    signal: requestOptions?.abortSignal,
                    eventShape: {
                        type: "sse",
                        streamTerminator: "[DONE]",
                    },
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /messaging/v1/messages/stream.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Regenerate ``interaction_id`` on the thread against the live version, then
     * replay ``text`` onto the clone. The acting user is optional — absent for the
     * agent-scoped publishable-key flow, where IA attributes the thread's own user.
     * ``thread_id`` in the response is the clone's id, not the original.
     *
     * @param {string} threadId
     * @param {Apollo.RerunMessageRequest} request
     * @param {Messaging.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.messaging.rerun("threadId", {
     *         agent_id: "agent_id",
     *         interaction_id: "interaction_id",
     *         text: "text"
     *     })
     */
    public rerun(
        threadId: string,
        request: Apollo.RerunMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<Apollo.SendMessageResponse> {
        return core.HttpResponsePromise.fromPromise(this.__rerun(threadId, request, requestOptions));
    }

    private async __rerun(
        threadId: string,
        request: Apollo.RerunMessageRequest,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.SendMessageResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `messaging/v1/threads/${core.url.encodePathParam(threadId)}/rerun`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.SendMessageResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /messaging/v1/threads/{threadId}/rerun.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * The thread transcript, scoped to the key's agent.
     *
     * @param {string} threadId
     * @param {Messaging.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.messaging.listMessages("threadId")
     */
    public listMessages(
        threadId: string,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<Apollo.Message[]> {
        return core.HttpResponsePromise.fromPromise(this.__listMessages(threadId, requestOptions));
    }

    private async __listMessages(
        threadId: string,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.Message[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `messaging/v1/threads/${core.url.encodePathParam(threadId)}/messages`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.Message[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /messaging/v1/threads/{threadId}/messages.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Every interaction trace in the thread.
     *
     * @param {string} threadId
     * @param {Messaging.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.messaging.threadTrace("threadId")
     */
    public threadTrace(
        threadId: string,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<Apollo.Trace[]> {
        return core.HttpResponsePromise.fromPromise(this.__threadTrace(threadId, requestOptions));
    }

    private async __threadTrace(
        threadId: string,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.Trace[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `messaging/v1/threads/${core.url.encodePathParam(threadId)}/trace`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.Trace[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /messaging/v1/threads/{threadId}/trace.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * One interaction's trace, resolved directly by interaction id.
     *
     * @param {string} interactionId
     * @param {Messaging.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.messaging.interactionTrace("interactionId")
     */
    public interactionTrace(
        interactionId: string,
        requestOptions?: Messaging.RequestOptions,
    ): core.HttpResponsePromise<Apollo.Trace> {
        return core.HttpResponsePromise.fromPromise(this.__interactionTrace(interactionId, requestOptions));
    }

    private async __interactionTrace(
        interactionId: string,
        requestOptions?: Messaging.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.Trace>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `messaging/v1/interactions/${core.url.encodePathParam(interactionId)}/trace`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.Trace, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /messaging/v1/interactions/{interactionId}/trace.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
