// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         created_from: "2024-01-15T09:30:00Z",
 *         created_to: "2024-01-15T09:30:00Z"
 *     }
 */
export interface GetAgentUsageRequest {
    /** Start of the usage window (RFC 3339). Maps to created>=. */
    created_from?: string;
    /** End of the usage window (RFC 3339). Maps to created<=. */
    created_to?: string;
}
