// This file was auto-generated by Fern from our API Definition.

export const ListVersionsRequestStatusItem = {
    Draft: "draft",
    Published: "published",
    Archived: "archived",
} as const;
export type ListVersionsRequestStatusItem =
    (typeof ListVersionsRequestStatusItem)[keyof typeof ListVersionsRequestStatusItem];
