// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace Auth {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Auth {
    protected readonly _options: Auth.Options;

    constructor(_options: Auth.Options) {
        this._options = _options;
    }

    /**
     * Exchange a credential for a short-lived access token (OAuth 2.0, RFC 6749). Supported grant types: `publishable_key`. Refresh and other grants will be added on the same endpoint.
     *
     * @param {Record<string, unknown>} request
     * @param {Auth.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.BadGatewayError}
     *
     * @example
     *     await client.auth.issueToken({
     *         "grant_type": "publishable_key",
     *         "publishable_key": "pk_network_..."
     *     })
     */
    public issueToken(
        request: Record<string, unknown>,
        requestOptions?: Auth.RequestOptions,
    ): core.HttpResponsePromise<Apollo.TokenResponse> {
        return core.HttpResponsePromise.fromPromise(this.__issueToken(request, requestOptions));
    }

    private async __issueToken(
        request: Record<string, unknown>,
        requestOptions?: Auth.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.TokenResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-organization-api-key": requestOptions?.organizationApiKey ?? this._options?.organizationApiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "management/v1/auth/token",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.TokenResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 502:
                    throw new Apollo.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /management/v1/auth/token.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
