// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         "page[size]": 1,
 *         "page[after]": "page[after]",
 *         "page[before]": "page[before]",
 *         sort_by: "sort_by",
 *         sort_order: "asc"
 *     }
 */
export interface ListProjectsRequest {
    "page[size]"?: number;
    "page[after]"?: string;
    "page[before]"?: string;
    sort_by?: string;
    sort_order?: Apollo.ListProjectsRequestSortOrder;
}
