// This file was auto-generated by Fern from our API Definition.

export const Actor = {
    User: "user",
    ThreeP: "3p",
    Agent: "agent",
} as const;
export type Actor = (typeof Actor)[keyof typeof Actor];
