// This file was auto-generated by Fern from our API Definition.

/**
 * Returns the updated agent.
 */
export interface AgentUpdateResponse {
    /** Agent id */
    id: string;
    /** Owning project id */
    project_id: string;
    /** Agent name */
    name: string;
    /** Tag of the currently deployed version; None until deployed */
    live_version_id?: string;
    /** Creation timestamp */
    created_at: string;
    /** Last update timestamp */
    updated_at: string;
}
