// This file was auto-generated by Fern from our API Definition.

/**
 * Result of a push. ``gcs_key`` (raw storage path) is not exposed.
 */
export interface AgentVersionPushResponse {
    agent_id: string;
    version_id: string;
    new_version_revision_number: number;
    new_version_tag: string;
    /** Id of the newly committed revision */
    revision_id: string;
    /** Hex-encoded SHA-256 of the canonical bundle bytes */
    sha256: string;
    size: number;
    created_at: string;
    commit_message?: string;
}
