// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Returns the updated version.
 */
export interface AgentVersionUpdateResponse {
    /** Version id */
    id: string;
    /** Owning agent id */
    agent_id: string;
    version_number: number;
    version_revision_number: number;
    /** Canonical tag, e.g. 'v3.2' */
    version_tag: string;
    status: AgentVersionUpdateResponse.Status;
    /** Lineage: cloned from */
    parent_version_id?: string;
    label?: string;
    tags?: string[];
    notes?: string;
    stats?: Apollo.VersionStats;
    created_at: string;
    published_at?: string;
}

export namespace AgentVersionUpdateResponse {
    export const Status = {
        Draft: "draft",
        Published: "published",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
