// This file was auto-generated by Fern from our API Definition.

/**
 * Query filters for listing an agent's versions (sort/pagination come from
 * the shared page-query dependency, not from here).
 */
export interface AgentVersionListFilters {
    status?: AgentVersionListFilters.Status.Item[];
    /** Filter by tag (partial match) */
    tag?: string;
    /** Filter by version number (exact match) */
    version_number?: number;
    /** Filter by label (partial match) */
    label?: string;
    /** If true, only return base versions (revision 0) */
    exclude_revisions?: boolean;
}

export namespace AgentVersionListFilters {
    export type Status = Status.Item[];

    export namespace Status {
        export const Item = {
            Draft: "draft",
            Published: "published",
            Archived: "archived",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
