// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface Card {
    id: string;
    name: string;
    category: string;
    query?: Record<string, unknown>;
    parameters: Apollo.CardParameter[];
    sub_entities?: Apollo.MessageCardSubEntity[];
    self_review?: Apollo.TaskInteractionOptionSelfReview;
    is_recommended: boolean;
}
