// This file was auto-generated by Fern from our API Definition.

export interface CreateExternalTaskResponse {
    id: string;
    user_id: string;
    title: string;
    welcome_message?: string;
    followup_suggestions?: string[];
}
