// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface CreateTopicRequestBody {
    title?: string;
    params?: Apollo.TaskParameter[];
    entities?: Apollo.TaskTopicEntity[];
    static_context?: Record<string, unknown>[];
}
