// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface EntityItemSubEntity {
    name: string;
    items: Apollo.EntityItemSubEntityItem[];
}
