// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * The error body an end user receives when interacting with Apollo.
 *
 * ``code`` is the stable, machine-readable branch point clients switch on.
 * ``message`` is human-readable and explicitly NOT part of the contract --
 * it may change at any time and must never be parsed.
 */
export interface ErrorBody {
    /** Stable, namespaced machine code clients branch on (e.g. "not_found" or "agents.not_found"). THE branch point -- open/extensible, append-only. */
    code: string;
    /** Human-readable explanation. NOT part of the contract; may change anytime. Clients must never parse or branch on this. */
    message: string;
    /** Trace id for support correlation. */
    request_id?: string;
    /** Optional structured sub-errors (e.g. per-field validation failures). */
    details?: Apollo.ErrorDetail[];
}
