// This file was auto-generated by Fern from our API Definition.

/**
 * type=error — either a session-level error (seq -1) or an error raised while processing the turn.
 */
export interface ErrorEnvelope {
    type?: "error";
    data?: ErrorEnvelope.Data;
    /** Monotonic sequence for gap detection / replay. Locally-generated errors use -1. */
    seq: number;
}

export namespace ErrorEnvelope {
    export type Data =
        /**
         * Session-level error (invalid frame, insufficient balance, connection loss). */
        | {
              error: string;
              code?: number | undefined;
          }
        /**
         * Error raised while processing the turn. */
        | {
              message?: string | undefined;
              status_code?: number | undefined;
              error_code?: string | undefined;
          };
}
