// This file was auto-generated by Fern from our API Definition.

/**
 * A single structured sub-error (e.g. one field's validation failure).
 */
export interface ErrorDetail {
    field?: string;
    message: string;
}
