// This file was auto-generated by Fern from our API Definition.

/**
 * type=error — either a locally-generated error (seq -1) or a forwarded IA error.
 */
export interface ErrorEnvelope {
    type?: "error";
    data?: ErrorEnvelope.Data;
    /** Monotonic sequence for gap detection / replay. Locally-generated errors use -1. */
    seq: number;
}

export namespace ErrorEnvelope {
    export type Data =
        /**
         * Locally generated (bad frame, wallet-gate denial, relay loss). */
        | {
              error: string;
              code?: number | undefined;
          }
        /**
         * Forwarded IA error payload. */
        | {
              message?: string | undefined;
              status_code?: number | undefined;
              error_code?: string | undefined;
          };
}
