// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * type=event — a raw IA event forwarded per the allow-list.
 */
export interface EventEnvelope {
    type?: "event";
    data?: Apollo.IaEvent;
    /** Monotonic sequence for gap detection / replay. Locally-generated errors use -1. */
    seq: number;
}
