// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * type=event — a streaming event emitted while the agent works.
 */
export interface EventEnvelope {
    type?: "event";
    data?: Apollo.StreamEvent;
    /** Monotonic sequence for gap detection / replay. Locally-generated errors use -1. */
    seq: number;
}
