// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ExternalPageAgentVersion {
    results: Apollo.AgentVersion[];
    meta: Apollo.ExternalPageMeta;
    links: Apollo.ExternalPageLinks;
}
