// This file was auto-generated by Fern from our API Definition.

import type * as AuiApi from "../index.js";

export interface ExternalTaskMessage {
    id: string;
    created_at: string;
    text: string;
    sender: AuiApi.ExternalTaskMessageContactParty;
    receiver: AuiApi.ExternalTaskMessageContactParty;
    options: AuiApi.ExternalTaskMessageOption[];
    variants_options: AuiApi.ExternalTaskMessageOption[];
    followup_suggestions: string[];
}
