// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ExternalPageExternalAgent {
    results: Apollo.ExternalAgent[];
    meta: Apollo.ExternalPageMeta;
    links: Apollo.ExternalPageLinks;
}
