// This file was auto-generated by Fern from our API Definition.

import type * as AuiApi from "../index.js";

export interface FinalMessagePayload {
    id: string;
    created_at: string;
    /** Complete response text */
    text: string;
    sender: AuiApi.WsActor;
    receiver: AuiApi.WsActor;
    /** Product recommendation cards */
    cards?: AuiApi.ProductCard[];
    /** Suggested follow-up questions */
    followup_suggestions?: string[];
}
