// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface FinalMessagePayload {
    id: string;
    created_at: string;
    /** Complete response text */
    text: string;
    sender: Apollo.WsActor;
    receiver: Apollo.WsActor;
    /** Product recommendation cards */
    cards?: Apollo.ProductCard[];
    /** Suggested follow-up questions */
    followup_suggestions?: string[];
}
