// This file was auto-generated by Fern from our API Definition.

export interface InitiateThreadResponse {
    /** Thread the opener landed on (new or continued). */
    thread_id: string;
    /** Provider message id for the sent opener. */
    message_sid: string;
}
