// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface LatencyMetadata {
    elapsed: number;
    unit?: Apollo.LatencyUnit;
    time_to_first_token?: number;
}
