// This file was auto-generated by Fern from our API Definition.

export const LatencyUnit = {
    Microsecond: "microsecond",
    Millisecond: "millisecond",
    Second: "second",
    Minute: "minute",
} as const;
export type LatencyUnit = (typeof LatencyUnit)[keyof typeof LatencyUnit];
