// This file was auto-generated by Fern from our API Definition.

import type * as AuiApi from "../index.js";

export interface ListExternalTasksResponse {
    tasks?: AuiApi.CreateExternalTaskResponse[];
    total: number;
    page: number;
    size: number;
}
