// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Structured form of the card. `entity` is a flat {code: value} map of the card's fields; `sub_entities` holds nested groups such as product variants. Keys are defined by the agent's card templates.
 */
export interface MessageCardJsonData {
    entity?: Record<string, unknown>;
    sub_entities?: Apollo.MessageCardSubEntity[];
}
