// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Terminal event of a turn: the completed agent reply.
 */
export interface MessageStreamEvent {
    /** Monotonic sequence number; echo the last seen value via Last-Event-ID to resume. */
    seq: number;
    data: Apollo.Message;
}
