// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * One message in a thread transcript.
 */
export interface Message {
    /** Interaction id (or message id for interaction-less messages). */
    id: string;
    /** ISO-8601. */
    created_at?: string;
    text?: string;
    sender?: Apollo.MessageParty;
    receiver?: Apollo.MessageParty;
    cards?: Apollo.MessageCard[];
    welcome_message?: string;
    followup_suggestions?: string[];
    url?: string;
    input_tokens?: number;
    output_tokens?: number;
}
