// This file was auto-generated by Fern from our API Definition.

/** How ``offset`` is combined with the target for ``gt_offset`` / ``lte_offset`` / etc. */
export const OffsetType = {
    Add: "add",
    Subtract: "subtract",
} as const;
export type OffsetType = (typeof OffsetType)[keyof typeof OffsetType];
