// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface PageThreadListItem {
    results: Apollo.ThreadListItem[];
    meta: Apollo.PageMeta;
    links: Apollo.PageLinks;
}
