// This file was auto-generated by Fern from our API Definition.

export const ParameterPresenceLevel = {
    Mandatory: "MANDATORY",
    Optional: "OPTIONAL",
} as const;
export type ParameterPresenceLevel = (typeof ParameterPresenceLevel)[keyof typeof ParameterPresenceLevel];
