// This file was auto-generated by Fern from our API Definition.

export const ParameterType = {
    Boolean: "boolean",
    Numeric: "numeric",
    String: "string",
    Datetime: "datetime",
    Date: "date",
    Time: "time",
    Object: "object",
    ListOfObjects: "list_of_objects",
} as const;
export type ParameterType = (typeof ParameterType)[keyof typeof ParameterType];
