// This file was auto-generated by Fern from our API Definition.

export interface ProductParameter {
    /** Parameter name */
    title: string;
    /** Parameter value */
    value: ProductParameter.Value;
    type: ProductParameter.Type;
}

export namespace ProductParameter {
    /**
     * Parameter value
     */
    export type Value = string | number | unknown[];
    export const Type = {
        String: "string",
        Numeric: "numeric",
        Array: "array",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
