// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface ProductCard {
    id: string;
    name: string;
    parameters: Apollo.ProductParameter[];
    is_recommended?: boolean;
}
