// This file was auto-generated by Fern from our API Definition.

/**
 * A project — groups your agents within an organization.
 */
export interface Project {
    /** Project id */
    id: string;
    /** Project name */
    name: string;
    /** Creation timestamp */
    created_at: string;
    /** Last update timestamp */
    updated_at: string;
}
