// This file was auto-generated by Fern from our API Definition.

/**
 * The published Project shape (SDK entity: ``Project``).
 */
export interface Project {
    /** Project id */
    id: string;
    /** Project name */
    name: string;
    /** Creation timestamp */
    created_at: string;
    /** Last update timestamp */
    updated_at: string;
}
