// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface RecordScope {
    network_id?: string;
    account_id?: string;
    seed_id?: string;
    network_category_id?: string;
    type?: Apollo.RecordScopeType;
}
