// This file was auto-generated by Fern from our API Definition.

export const RecordScopeType = {
    Network: "NETWORK",
    Account: "ACCOUNT",
    Seed: "SEED",
    NetworkCategory: "NETWORK_CATEGORY",
    Global: "GLOBAL",
} as const;
export type RecordScopeType = (typeof RecordScopeType)[keyof typeof RecordScopeType];
