// This file was auto-generated by Fern from our API Definition.

export const RecordOriginType = {
    Stores: "stores",
    WebWidget: "web-widget",
    InspectionPlayground: "inspection-playground",
    FeedbackPlayground: "feedback-playground",
    LlmManagement: "llm-management",
    ThirdParty: "third-party",
} as const;
export type RecordOriginType = (typeof RecordOriginType)[keyof typeof RecordOriginType];
