// This file was auto-generated by Fern from our API Definition.

export interface ResumeRequest {
    type: "resume";
    /** Replay buffered envelopes with seq > resume_after for the active thread. */
    resume_after: number;
}
