// This file was auto-generated by Fern from our API Definition.

/**
 * Send-message contract. ``agent_id`` is required; org comes from the gateway
 * header, not the body. ``thread_id`` is optional: present -> append to that
 * thread; absent -> a new thread is auto-created and its id returned.
 */
export interface SendMessageRequest {
    agent_id: string;
    text: string;
    user_id: string;
    thread_id?: string;
    /** Signed image URL for vision input; forwarded to IA as body.image.signed_url. */
    image_url?: string;
}
