// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * A leaf condition in a when clause. Combines a method (what to check),
 * params/entities (what to check on), an operation (how to compare),
 * and a value (what to compare against).
 */
export interface SimpleViewCondition {
    method: SimpleViewCondition.Method;
    /** List of param codes (can be empty) */
    params?: string[];
    /** Optional entity context */
    entities?: string[];
    /** Optional sub-entity context in case of checking sub-entity param value as source and not entity, entities and params should be filled when filling sub_entities */
    sub_entities?: string[];
    /** Optional operation, in case of having more than one param under params, then the only allowed operations are  all_has_value and any_has_value */
    operation?: Apollo.SimpleViewOperation;
    /** Value to compare against. Can be a literal (string, number, boolean). */
    value?: SimpleViewCondition.Value;
    /** Target param code to compare against instead of static value as value will be null when this is filled. */
    target_param?: string;
    /** Target entity name to fetch target value to compare with by target_param instead of static value as value will be null when this is filled. */
    target_entity?: string;
    /** When target_entity is used, fetch the target value from desired entities only. Set false to include saved task entities too. Defaults to true when not set. */
    target_from_desired_only?: boolean;
    /** Multiple target param codes (e.g. gt_sum, gte_sum, lt_sum, lte_sum). Stored as target_param_ids in predicate kwargs. */
    target_params?: string[];
    /** Numeric offset: gt_offset/lte_offset margins, after_date_offset magnitude (with offset_unit), *_entity_sum / *_sum margins, etc. */
    offset?: SimpleViewCondition.Offset;
    /** For gt_offset / lte_offset: add or subtract (with offset) relative to the target value. */
    offset_type?: Apollo.OffsetType;
    /** For gt_percentage / lt_percentage / lte_percentage / gte_percentage: percentage of target value to compare against. */
    percentage?: SimpleViewCondition.Percentage;
    /** Calendar/time unit for offset fields: use with any offset-related operation (gt_offset, lte_offset, between_offset, after_date_offset, gt/gte/lt/lte_entity_sum, gt/gte/lt/lte_sum, etc.). */
    offset_unit?: Apollo.OffsetUnit;
    /** For between_offset: lower bound relative to target. */
    offset_min?: SimpleViewCondition.OffsetMin;
    /** For between_offset: upper bound relative to target. */
    offset_max?: SimpleViewCondition.OffsetMax;
    /** For gt/gte/lt/lte_entity_sum: aggregate function name (e.g. sum). */
    aggregate?: string;
    /** For gt/gte/lt/lte_entity_sum: filter on related entity records. */
    filter?: Record<string, unknown>;
}

export namespace SimpleViewCondition {
    export type Method = Apollo.SimpleViewMethod | string;
    /**
     * Value to compare against. Can be a literal (string, number, boolean).
     */
    export type Value = string | number | number | boolean | unknown[] | Record<string, unknown>;
    /**
     * Numeric offset: gt_offset/lte_offset margins, after_date_offset magnitude (with offset_unit), *_entity_sum / *_sum margins, etc.
     */
    export type Offset = number | number;
    /**
     * For gt_percentage / lt_percentage / lte_percentage / gte_percentage: percentage of target value to compare against.
     */
    export type Percentage = number | number;
    /**
     * For between_offset: lower bound relative to target.
     */
    export type OffsetMin = number | number;
    /**
     * For between_offset: upper bound relative to target.
     */
    export type OffsetMax = number | number;
}
