// This file was auto-generated by Fern from our API Definition.

export interface SimulatorCommand {
    type: SimulatorCommand.Type;
    /** IA SimulationRequest payload, relayed verbatim. For `start`, must carry `task_id` (used for the wallet gate, replay buffer, and billing). */
    data?: SimulatorCommand.Data;
}

export namespace SimulatorCommand {
    export const Type = {
        Start: "start",
        Cancel: "cancel",
        ForceCancel: "force-cancel",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    /**
     * IA SimulationRequest payload, relayed verbatim. For `start`, must carry `task_id` (used for the wallet gate, replay buffer, and billing).
     */
    export interface Data {
        task_id?: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
