// This file was auto-generated by Fern from our API Definition.

/**
 * Streaming event. Which event types are delivered depends on the `events` query parameter chosen when opening the session.
 */
export interface StreamEvent {
    channel?: StreamEvent.Channel;
    scope?: Record<string, unknown>;
    /** Event-specific payload. Token deltas carry `data.text`. */
    data?: unknown;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace StreamEvent {
    export interface Channel {
        /** Default stream: thread-message-text-content-updated (token delta), thread-message-text-content-completed (stream end). ?events=all|verbose adds the full workflow/lifecycle set. */
        event_name?: string;
    }
}
