// This file was auto-generated by Fern from our API Definition.

export interface StreamingUpdatePayload {
    channel: StreamingUpdatePayload.Channel;
    scope?: StreamingUpdatePayload.Scope;
    data: StreamingUpdatePayload.Data;
    timestamp?: string;
}

export namespace StreamingUpdatePayload {
    export interface Channel {
        type: "WEBSOCKET";
        /** Unique channel identifier */
        channel_name: string;
        event_name: "thread-message-text-content-updated";
    }

    export interface Scope {
        type?: "LLM_ACTIVATION_EXECUTION";
        data?: Scope.Data;
        context?: Scope.Context;
    }

    export namespace Scope {
        export interface Data {
            status?: Data.Status;
        }

        export namespace Data {
            export const Status = {
                Success: "SUCCESS",
                Failed: "FAILED",
                Pending: "PENDING",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }

        export interface Context {
            message_id?: string;
            task_id?: string;
            interaction_id?: string;
            pillar?: string;
        }
    }

    export interface Data {
        /** Streaming text content */
        text: string;
    }
}
