// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Follow-up prompt suggestions generated after the reply — emitted after the
 * terminal ``message`` event, on turns whose message carried no suggestions of
 * its own (generation costs a model round trip, so it never delays the reply).
 * Optional: absent when the message already carried suggestions, and never
 * emitted by agents on the v1 engine.
 */
export interface SuggestionsStreamEvent {
    /** Monotonic sequence number; echo the last seen value via Last-Event-ID to resume. */
    seq: number;
    data: Apollo.SuggestionsStreamEventData;
}
