// This file was auto-generated by Fern from our API Definition.

export const TaskInteractionFacetsTaskParametersMatchGroup = {
    Hard: "HARD",
    Soft: "SOFT",
} as const;
export type TaskInteractionFacetsTaskParametersMatchGroup =
    (typeof TaskInteractionFacetsTaskParametersMatchGroup)[keyof typeof TaskInteractionFacetsTaskParametersMatchGroup];
