// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TaskParameter {
    param: string;
    title: string;
    type?: Apollo.TaskParameterType;
    value?: TaskParameter.Value;
    value_history?: (TaskParameter.ValueHistory.Item | undefined)[];
    presence_level?: Apollo.ParameterPresenceLevel;
    facet_match_group?: Apollo.TaskInteractionFacetsTaskParametersMatchGroup;
    is_anchor?: boolean;
    is_value_filled?: boolean;
    is_visible?: boolean;
    is_exist_param?: boolean;
    param_type?: Apollo.ParameterType;
    code?: string;
}

export namespace TaskParameter {
    /**
     * Value to compare against. Can be a literal (string, number, boolean).
     */
    export type Value = string | number | number | boolean | unknown[] | Record<string, unknown>;
    export type ValueHistory = ValueHistory.Item[];

    export namespace ValueHistory {
        export type Item = Apollo.TaskParameterValue | Apollo.TaskParameterRangeValue;
    }
}
