// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TaskTopicEntityItem {
    id?: string;
    parameters?: Apollo.EntityItemParameter[];
    fields?: Record<string, unknown>;
    identifier?: unknown;
    sub_entities?: Apollo.EntityItemSubEntity[];
    self_review?: Apollo.TaskInteractionOptionSelfReview;
    is_visible?: boolean;
    workflow?: string;
    query?: Record<string, unknown>;
    index?: number;
}
