// This file was auto-generated by Fern from our API Definition.

export const TaskInteractionOptionSelfReviewScoreLabel = {
    High: "HIGH",
    Medium: "MEDIUM",
    Low: "LOW",
} as const;
export type TaskInteractionOptionSelfReviewScoreLabel =
    (typeof TaskInteractionOptionSelfReviewScoreLabel)[keyof typeof TaskInteractionOptionSelfReviewScoreLabel];
