// This file was auto-generated by Fern from our API Definition.

export interface TextConversationInitiateResponse {
    status: boolean;
    data: Record<string, string>;
    message: string;
    statusCode: number;
}
