// This file was auto-generated by Fern from our API Definition.

/**
 * Query params for ``GET /management/v1/threads`` — the thread-filter DSL.
 *
 * The full grammar is modeled and shape-validated here; malformed values 422 at
 * the boundary. Translation to intelligent-agent, and rejection of the filters it
 * doesn't serve, lives in ``mapping.internal_thread_filters_from_external``.
 */
export interface ThreadListFilters {
    /** Filter by project (account) id */
    project_id?: string;
    /** Filter by end-user id */
    user_id?: string;
    /** Filter by caller-supplied external id */
    external_id?: string;
    /** RFC3339 timestamp(s); two values = a [start, end] range */
    created?: string[];
    /** Filter by activated tool code(s) */
    tool?: string[];
    /** Rule 'code', or 'code:fired|blocked|passed' */
    rule?: string[];
    /** 'key:value', 'key:*', or 'key' with >,<,>=,<= */
    param?: string[];
    /** Filter by agent id(s) */
    agent_id?: string[];
}
