// This file was auto-generated by Fern from our API Definition.

/**
 * Query filters for listing threads. Repeatable filters (``tool``,
 * ``rule``, ``param``, ``created``) OR within a field and AND across fields.
 */
export interface ThreadListFilters {
    /** Filter by project (account) id */
    project_id?: string;
    /** Filter by end-user id */
    user_id?: string;
    /** Filter by caller-supplied external id */
    external_id?: string;
    /** RFC3339 timestamp(s); two values = a [start, end] range */
    created?: string[];
    /** Filter by activated tool code(s) */
    tool?: string[];
    /** Rule 'code', or 'code:fired|blocked|passed' */
    rule?: string[];
    /** 'key:value', 'key:*', or 'key' with >,<,>=,<= */
    param?: string[];
    /** Filter by agent id(s) */
    agent_id?: string[];
}
