// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * First event of a stream: the resolved thread id (a client can't read
 * response headers mid-stream). Unsequenced — it replays on every resume.
 */
export interface ThreadStreamEvent {
    data: Apollo.ThreadStreamEventData;
}
