// This file was auto-generated by Fern from our API Definition.

export interface ThreadStreamEventData {
    /** Thread the turn runs on (newly created when the request omitted it). */
    thread_id: string;
}
