// This file was auto-generated by Fern from our API Definition.

export interface Thread {
    /** Thread id */
    id: string;
    /** End-user this thread belongs to, if any */
    user_id?: string;
    /** Thread title */
    title: string;
    /** Agent's opening message */
    welcome_message?: string;
    /** Suggested follow-up prompts */
    followup_suggestions?: string[];
}
