// This file was auto-generated by Fern from our API Definition.

export interface ThreadListItem {
    /** Thread id */
    id: string;
    /** Thread title */
    title?: string;
    /** Creation timestamp (ISO-8601) */
    created_at?: string;
    /** Agent version tag the thread runs on */
    version_tag?: string;
}
