// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceResponse {
    type?: string;
    message?: string;
    suggestions?: string[];
    question_reason?: string;
    asking_for?: string[];
    block_message?: string;
    error?: string;
    jsx_widgets?: Apollo.TraceJsxWidget[];
}
