// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceEntity {
    entity: string;
    identifier?: string;
    reference?: string;
    source: Apollo.TraceEntitySource;
    params?: Record<string, unknown>;
    sub_entities?: Apollo.TraceSubEntity[];
}
