// This file was auto-generated by Fern from our API Definition.

/** Schema: all_filled | missing_required | missing_optional_ask_once. */
export const TraceParamsCheckStatus = {
    AllFilled: "all_filled",
    MissingRequired: "missing_required",
    MissingOptional: "missing_optional",
    MissingOptionalAskOnce: "missing_optional_ask_once",
} as const;
export type TraceParamsCheckStatus = (typeof TraceParamsCheckStatus)[keyof typeof TraceParamsCheckStatus];
