// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceRuleTriggerEvaluation {
    code: string;
    triggered: boolean;
    reason?: Apollo.TraceRuleConditionResult[];
}
