// This file was auto-generated by Fern from our API Definition.

/** Schema: active_tool | intent_classification | structured. */
export const TraceTriggerType = {
    Structured: "structured",
    IntentClassification: "intent_classification",
    ActiveTool: "active_tool",
    Rule: "rule",
    SubTool: "sub_tool",
} as const;
export type TraceTriggerType = (typeof TraceTriggerType)[keyof typeof TraceTriggerType];
