// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceContext {
    active_tools?: Apollo.TraceActiveTool[];
    entities?: Apollo.TraceEntity[];
    static_context?: Record<string, unknown>[];
    message_params?: Record<string, unknown>;
    response_params?: Record<string, unknown>;
}
