// This file was auto-generated by Fern from our API Definition.

/** Schema: answer | question | blocked | confirmation_request | error. */
export const TraceResponseType = {
    Answer: "answer",
    Question: "question",
    Blocked: "blocked",
    ConfirmationRequest: "confirmation_request",
    Error: "error",
} as const;
export type TraceResponseType = (typeof TraceResponseType)[keyof typeof TraceResponseType];
