// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * One decision the agent took while handling the message.
 */
export interface TraceDecision {
    type?: string;
    tool?: string;
    parent_tool?: string;
    track_id?: string;
    status?: string;
    check_status?: string;
    trigger?: Apollo.TraceTrigger;
    trigger_type?: string;
    rule?: Apollo.TraceRule;
    text?: string;
    fail_reason?: string;
    computation?: string;
    output_param?: string;
    output_title?: string;
    qualified?: boolean;
    matched_branch?: string;
}
