// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceSelfReviewEntity {
    entity: string;
    identifier?: TraceSelfReviewEntity.Identifier;
    reference?: string;
    self_review?: Apollo.TraceSelfReviewSection;
    is_visible: boolean;
}

export namespace TraceSelfReviewEntity {
    export type Identifier = string | number;
}
