// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceRuleMissingInfo {
    type: Apollo.TraceRuleType;
    action?: Apollo.TraceRuleAction;
    reason?: string;
    params_added?: Record<string, unknown>;
    excluded_entities?: string[];
    code?: string;
    required_missing_params_by_group?: string[][];
}
