// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceUnderstanding {
    intents?: string[];
    guardrails?: Apollo.TraceGuardrails;
}
