// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceRuleParamsMissing {
    type?: Apollo.TraceRuleType;
    action?: Apollo.TraceRuleAction;
    missing_params?: string[];
    reason?: string;
}
