// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionParamsCheck {
    type?: Apollo.TraceDecisionType;
    tool: string;
    status: Apollo.TraceParamsCheckStatus;
    /** Per mandatory (required) group; inner list = unfilled param codes for that group. */
    required_missing_params_by_group?: string[][];
    /** Per optional group; inner list = unfilled param codes for that group. */
    optional_missing_params_by_group?: string[][];
    track_id?: string;
}
