// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * MCP integration call details.
 */
export interface TraceMcpIntegration {
    code: string;
    type?: Apollo.TraceIntegrationType;
    name: string;
    completion: string;
    tool_calls?: Apollo.TraceMcpToolCall[];
}
