// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Constraint rule with QUERY-derived preview; only this rule subtype carries confirmation_preview.
 */
export interface TraceRuleAskForConfirmation {
    type: Apollo.TraceRuleType;
    action?: "ASK_FOR_CONFIRMATION";
    reason?: string;
    params_added?: Record<string, unknown>;
    excluded_entities?: string[];
    code?: string;
    confirmation_preview?: Record<string, unknown>[];
}
