// This file was auto-generated by Fern from our API Definition.

/** Schema: no_tool | activate_tool | params_check | rule_triggered | call_integration | ask_question | ask_confirmation | block | self_review. */
export const TraceDecisionType = {
    NoTool: "no_tool",
    ActivateTool: "activate_tool",
    ActivateSubTool: "activate_sub_tool",
    ParamsCheck: "params_check",
    RuleTriggered: "rule_triggered",
    CallIntegration: "call_integration",
    AskQuestion: "ask_question",
    AskConfirmation: "ask_confirmation",
    Block: "block",
    SelfReview: "self_review",
    ToolTextResponse: "tool_text_response",
} as const;
export type TraceDecisionType = (typeof TraceDecisionType)[keyof typeof TraceDecisionType];
