// This file was auto-generated by Fern from our API Definition.

/** Schema: missing_params | from_rule | clarification. Why asking a question. */
export const TraceQuestionReason = {
    MissingParams: "missing_params",
    FromRule: "from_rule",
    Clarification: "clarification",
} as const;
export type TraceQuestionReason = (typeof TraceQuestionReason)[keyof typeof TraceQuestionReason];
