// This file was auto-generated by Fern from our API Definition.

export interface TraceJsxWidget {
    name?: string;
    category?: string;
    rendered_jsx?: string;
    is_recommended?: boolean;
    index?: number;
}
