// This file was auto-generated by Fern from our API Definition.

/** Entity source. Schema enum: external_context | user_message | response_mapping. */
export const TraceEntitySource = {
    ExternalContext: "external_context",
    UserMessage: "user_message",
    ResponseMapping: "response_mapping",
} as const;
export type TraceEntitySource = (typeof TraceEntitySource)[keyof typeof TraceEntitySource];
