// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Schema: type (required); params, matched_objective, reason (optional).
 */
export interface TraceTrigger {
    type: Apollo.TraceTriggerType;
    reasons?: string[];
    matched_objective?: string;
}
