// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceSelfReviewEntity {
    entity: string;
    identifier?: string;
    reference?: string;
    sub_entities?: Apollo.TracSelfReviewSubEntity[];
    self_review?: Apollo.TraceSelfReviewSection;
    is_visible: boolean;
}
