// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceRuleReason {
    passed?: boolean;
    trigger_type?: string;
    condition?: Apollo.TraceCondition;
}
