// This file was auto-generated by Fern from our API Definition.

export interface TraceIntegrationRequest {
    name: string;
    url: string;
    method: string;
    category: string;
    params?: unknown;
}
