// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * Reasoning trace for the interaction, embedded only when include_trace=true. Same shape as the REST `Trace` model (GET /messaging/v1/threads/{threadId}/trace); summarized here.
 */
export interface Trace {
    input?: Apollo.TraceInput;
    understanding?: Record<string, unknown>;
    decisions?: Record<string, unknown>[];
    computed_parameters?: Record<string, unknown>[];
    response?: Record<string, unknown>;
    rules_evaluations?: Record<string, unknown>[];
}
