// This file was auto-generated by Fern from our API Definition.

/** Schema: REST | MCP | RAG | INTERNAL_CONTEXT | STRUCTURED | GEN_AI. */
export const TraceIntegrationType = {
    Rest: "REST",
    Mcp: "MCP",
    Rag: "RAG",
    InternalContext: "INTERNAL_CONTEXT",
    Structured: "STRUCTURED",
    GenAi: "GEN_AI",
} as const;
export type TraceIntegrationType = (typeof TraceIntegrationType)[keyof typeof TraceIntegrationType];
