// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceDecisionAskForConfirmation {
    type?: Apollo.TraceDecisionType;
    tool: string;
    confirmation_preview?: Record<string, unknown>[];
    track_id?: string;
}
