// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * RAG (knowledge hub) integration call details.
 */
export interface TraceRagIntegration {
    code: string;
    type?: Apollo.TraceIntegrationType;
    request: Apollo.TraceRagRequest;
    response?: Apollo.TraceRagResponse;
}
