// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface TraceMcpToolCall {
    tool_name: string;
    request_parameters?: Record<string, unknown>;
    response?: unknown;
    is_error?: boolean;
    latency?: Apollo.LatencyMetadata;
}
