// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

/**
 * REST API integration call details.
 */
export interface TraceRestIntegration {
    code: string;
    type?: Apollo.TraceIntegrationType;
    requests: Apollo.TraceIntegrationRequest[];
    response?: TraceRestIntegration.Response;
    status_code?: number;
    error_message?: string;
}

export namespace TraceRestIntegration {
    export type Response = Record<string, Apollo.TraceIntegrationResponse[]> | unknown;
}
