// This file was auto-generated by Fern from our API Definition.

/**
 * Usage metrics for one agent or across a project over the requested window.
 */
export interface UsageResponse {
    /** Number of billed interactions (one per interaction). */
    interaction_count?: number;
    /** Total input tokens. */
    input_tokens?: number;
    /** Total output tokens. */
    output_tokens?: number;
    /** Total cached (read) input tokens. */
    cache_read_tokens?: number;
    /** Total reasoning tokens. */
    reasoning_tokens?: number;
    /** Sum of input + output + cache-read + reasoning tokens. */
    total_tokens?: number;
}
