// This file was auto-generated by Fern from our API Definition.

/**
 * Optional body for ``POST /welcome-message``. Omit entirely to keep the
 * static welcome; pass ``placeholders`` to seed ``dynamic_welcome_message``.
 */
export interface WelcomeMessageRequest {
    /** Placeholder name → value to seed into dynamic_welcome_message (e.g. {"page-title": "honda civic"}). */
    placeholders?: Record<string, string>;
}
