// This file was auto-generated by Fern from our API Definition.

export interface WorkflowMetadata {
    id: string;
    name: string;
    metadata?: Record<string, unknown>;
    produce_options?: boolean;
    is_internal_context?: boolean;
}
