// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../index.js";

export interface WorkflowsMetadataResponse {
    workflows?: Apollo.WorkflowMetadata[];
}
