// This file was auto-generated by Fern from our API Definition.

export interface WsActor {
    id: string;
    type: WsActor.Type;
    email?: string;
}

export namespace WsActor {
    export const Type = {
        User: "user",
        Agent: "agent",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
