// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace Webhooks {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Webhooks {
    protected readonly _options: Webhooks.Options;

    constructor(_options: Webhooks.Options) {
        this._options = _options;
    }

    /**
     * Enqueues an event for the agent bound to your webhook credential. Pass `text` and/or `agent_variables` as the agent's input, and an optional `thread_id` (your own conversation id) to continue an existing conversation — omit it to start a new one. A `202` means the event was durably accepted — processing happens asynchronously.
     *
     * @param {Apollo.WebhookEvent} request
     * @param {Webhooks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.webhooks.receiveAgentEvent()
     */
    public receiveAgentEvent(
        request: Apollo.WebhookEvent = {},
        requestOptions?: Webhooks.RequestOptions,
    ): core.HttpResponsePromise<Apollo.WebhookEventReceipt> {
        return core.HttpResponsePromise.fromPromise(this.__receiveAgentEvent(request, requestOptions));
    }

    private async __receiveAgentEvent(
        request: Apollo.WebhookEvent = {},
        requestOptions?: Webhooks.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.WebhookEventReceipt>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-organization-api-key": requestOptions?.organizationApiKey ?? this._options?.organizationApiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                "messaging/v1/events",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.WebhookEventReceipt, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError("Timeout exceeded when calling POST /messaging/v1/events.");
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
