// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as AuiApi from "../../../index.js";

export declare namespace ExternalApis {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ExternalApis {
    protected readonly _options: ExternalApis.Options;

    constructor(_options: ExternalApis.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {AuiApi.GetTasksByUserIdApiV1ExternalTasksGetRequest} request
     * @param {ExternalApis.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AuiApi.UnprocessableEntityError}
     *
     * @example
     *     await client.externalApis.getTasksByUserId({
     *         user_id: "user_id",
     *         page: 1,
     *         size: 1
     *     })
     */
    public getTasksByUserId(
        request: AuiApi.GetTasksByUserIdApiV1ExternalTasksGetRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): core.HttpResponsePromise<AuiApi.ListExternalTasksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTasksByUserId(request, requestOptions));
    }

    private async __getTasksByUserId(
        request: AuiApi.GetTasksByUserIdApiV1ExternalTasksGetRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): Promise<core.WithRawResponse<AuiApi.ListExternalTasksResponse>> {
        const { user_id: userId, page, size } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.user_id = userId;
        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (size != null) {
            _queryParams.size = size.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-network-api-key": requestOptions?.networkApiKey ?? this._options?.networkApiKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AuiApiEnvironment.Default)
                        .base,
                "api/v1/external/tasks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AuiApi.ListExternalTasksResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AuiApi.UnprocessableEntityError(
                        _response.error.body as AuiApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AuiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AuiApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AuiApiTimeoutError("Timeout exceeded when calling GET /api/v1/external/tasks.");
            case "unknown":
                throw new errors.AuiApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {AuiApi.CreateExternalTaskRequest} request
     * @param {ExternalApis.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AuiApi.UnprocessableEntityError}
     *
     * @example
     *     await client.externalApis.task({
     *         user_id: "user_id"
     *     })
     */
    public task(
        request: AuiApi.CreateExternalTaskRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): core.HttpResponsePromise<AuiApi.CreateExternalTaskResponse> {
        return core.HttpResponsePromise.fromPromise(this.__task(request, requestOptions));
    }

    private async __task(
        request: AuiApi.CreateExternalTaskRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): Promise<core.WithRawResponse<AuiApi.CreateExternalTaskResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-network-api-key": requestOptions?.networkApiKey ?? this._options?.networkApiKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AuiApiEnvironment.Default)
                        .base,
                "api/v1/external/tasks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AuiApi.CreateExternalTaskResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AuiApi.UnprocessableEntityError(
                        _response.error.body as AuiApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AuiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AuiApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AuiApiTimeoutError("Timeout exceeded when calling POST /api/v1/external/tasks.");
            case "unknown":
                throw new errors.AuiApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} taskId
     * @param {ExternalApis.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AuiApi.UnprocessableEntityError}
     *
     * @example
     *     await client.externalApis.getTaskMessages("task_id")
     */
    public getTaskMessages(
        taskId: string,
        requestOptions?: ExternalApis.RequestOptions,
    ): core.HttpResponsePromise<AuiApi.ExternalTaskMessage[]> {
        return core.HttpResponsePromise.fromPromise(this.__getTaskMessages(taskId, requestOptions));
    }

    private async __getTaskMessages(
        taskId: string,
        requestOptions?: ExternalApis.RequestOptions,
    ): Promise<core.WithRawResponse<AuiApi.ExternalTaskMessage[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-network-api-key": requestOptions?.networkApiKey ?? this._options?.networkApiKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AuiApiEnvironment.Default)
                        .base,
                `api/v1/external/tasks/${core.url.encodePathParam(taskId)}/messages`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AuiApi.ExternalTaskMessage[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AuiApi.UnprocessableEntityError(
                        _response.error.body as AuiApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AuiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AuiApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AuiApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/external/tasks/{task_id}/messages.",
                );
            case "unknown":
                throw new errors.AuiApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {AuiApi.SubmitExternalMessageRequest} request
     * @param {ExternalApis.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AuiApi.UnprocessableEntityError}
     *
     * @example
     *     await client.externalApis.message({
     *         is_external_api: true,
     *         task_id: "task_id",
     *         text: "text"
     *     })
     */
    public message(
        request: AuiApi.SubmitExternalMessageRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): core.HttpResponsePromise<AuiApi.ExternalTaskMessage> {
        return core.HttpResponsePromise.fromPromise(this.__message(request, requestOptions));
    }

    private async __message(
        request: AuiApi.SubmitExternalMessageRequest,
        requestOptions?: ExternalApis.RequestOptions,
    ): Promise<core.WithRawResponse<AuiApi.ExternalTaskMessage>> {
        const { is_external_api: isExternalApi, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (isExternalApi != null) {
            _queryParams.is_external_api = isExternalApi.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-network-api-key": requestOptions?.networkApiKey ?? this._options?.networkApiKey,
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.AuiApiEnvironment.Default)
                        .base,
                "api/v1/external/message",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as AuiApi.ExternalTaskMessage, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new AuiApi.UnprocessableEntityError(
                        _response.error.body as AuiApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AuiApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AuiApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AuiApiTimeoutError("Timeout exceeded when calling POST /api/v1/external/message.");
            case "unknown":
                throw new errors.AuiApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-network-api-key": apiKeyValue };
    }
}
