// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         runtime_version: "runtime_version"
 *     }
 */
export interface GetThreadRequest {
    /** Runtime generation the thread lives on: '1' (the default) reads threads of agents on the v1 runtime — today's behavior; any other value (e.g. '2' or '0.5.4') reads runtime-v2 threads. */
    runtime_version?: string;
}
