// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface UpdateThreadRequest {
    /** New thread title; omit to leave the title unchanged. */
    title?: string;
}
