// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         user_id: "user_id",
 *         page: 1,
 *         size: 1
 *     }
 */
export interface GetTasksByUserIdApiV1ExternalTasksGetRequest {
    user_id: string;
    page?: number;
    size?: number;
}
