// This file was auto-generated by Fern from our API Definition.

import type * as AuiApi from "../../../../index.js";

/**
 * @example
 *     {
 *         is_external_api: true,
 *         task_id: "task_id",
 *         text: "text"
 *     }
 */
export interface SubmitExternalMessageRequest {
    is_external_api?: boolean;
    task_id: string;
    text: string;
    context?: AuiApi.Context;
}
