// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as Apollo from "../../../index.js";

export declare namespace AgentVersions {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgentVersions {
    protected readonly _options: AgentVersions.Options;

    constructor(_options: AgentVersions.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {string} agentId
     * @param {Apollo.ListVersionsRequest} request
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.listVersions("agentId", {
     *         filters: {}
     *     })
     */
    public listVersions(
        agentId: string,
        request: Apollo.ListVersionsRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.ExternalPageAgentVersion> {
        return core.HttpResponsePromise.fromPromise(this.__listVersions(agentId, request, requestOptions));
    }

    private async __listVersions(
        agentId: string,
        request: Apollo.ListVersionsRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.ExternalPageAgentVersion>> {
        const {
            filters,
            "page[size]": pageSize,
            "page[after]": pageAfter,
            "page[before]": pageBefore,
            sort_by: sortBy,
            sort_order: sortOrder,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.filters = filters;
        if (pageSize != null) {
            _queryParams["page[size]"] = pageSize.toString();
        }

        if (pageAfter != null) {
            _queryParams["page[after]"] = pageAfter;
        }

        if (pageBefore != null) {
            _queryParams["page[before]"] = pageBefore;
        }

        if (sortBy != null) {
            _queryParams.sort_by = sortBy;
        }

        if (sortOrder != null) {
            _queryParams.sort_order = sortOrder;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.ExternalPageAgentVersion, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /management/v1/agents/{agentId}/versions.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {Apollo.AgentVersionCreateRequest} request
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.createVersion("agentId", {
     *         source: "version"
     *     })
     */
    public createVersion(
        agentId: string,
        request: Apollo.AgentVersionCreateRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createVersion(agentId, request, requestOptions));
    }

    private async __createVersion(
        agentId: string,
        request: Apollo.AgentVersionCreateRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionCreateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionCreateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /management/v1/agents/{agentId}/versions.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {string} versionId
     * @param {Apollo.AgentVersionUpdateRequest} request
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.updateVersion("agentId", "versionId")
     */
    public updateVersion(
        agentId: string,
        versionId: string,
        request: Apollo.AgentVersionUpdateRequest = {},
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateVersion(agentId, versionId, request, requestOptions));
    }

    private async __updateVersion(
        agentId: string,
        versionId: string,
        request: Apollo.AgentVersionUpdateRequest = {},
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionUpdateResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions/${core.url.encodePathParam(versionId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling PATCH /management/v1/agents/{agentId}/versions/{versionId}.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {string} versionId
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.publishVersion("agentId", "versionId")
     */
    public publishVersion(
        agentId: string,
        versionId: string,
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionPublishResponse> {
        return core.HttpResponsePromise.fromPromise(this.__publishVersion(agentId, versionId, requestOptions));
    }

    private async __publishVersion(
        agentId: string,
        versionId: string,
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionPublishResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions/${core.url.encodePathParam(versionId)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionPublishResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /management/v1/agents/{agentId}/versions/{versionId}/publish.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {string} versionId
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.archiveVersion("agentId", "versionId")
     */
    public archiveVersion(
        agentId: string,
        versionId: string,
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionArchiveResponse> {
        return core.HttpResponsePromise.fromPromise(this.__archiveVersion(agentId, versionId, requestOptions));
    }

    private async __archiveVersion(
        agentId: string,
        versionId: string,
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionArchiveResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions/${core.url.encodePathParam(versionId)}/archive`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionArchiveResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /management/v1/agents/{agentId}/versions/{versionId}/archive.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {string} versionId
     * @param {Apollo.AgentVersionPushRequest} request
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.pushVersion("agentId", "versionId", {
     *         caller: "agent_builder",
     *         bundle: {
     *             "key": "value"
     *         }
     *     })
     */
    public pushVersion(
        agentId: string,
        versionId: string,
        request: Apollo.AgentVersionPushRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionPushResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pushVersion(agentId, versionId, request, requestOptions));
    }

    private async __pushVersion(
        agentId: string,
        versionId: string,
        request: Apollo.AgentVersionPushRequest,
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionPushResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions/${core.url.encodePathParam(versionId)}/push`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionPushResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling POST /management/v1/agents/{agentId}/versions/{versionId}/push.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {string} agentId
     * @param {string} versionId
     * @param {Apollo.PullVersionRequest} request
     * @param {AgentVersions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Apollo.BadRequestError}
     * @throws {@link Apollo.UnauthorizedError}
     * @throws {@link Apollo.ForbiddenError}
     * @throws {@link Apollo.NotFoundError}
     * @throws {@link Apollo.ConflictError}
     * @throws {@link Apollo.UnprocessableEntityError}
     * @throws {@link Apollo.InternalServerError}
     *
     * @example
     *     await client.agentVersions.pullVersion("agentId", "versionId", {
     *         version_tag: "version_tag"
     *     })
     */
    public pullVersion(
        agentId: string,
        versionId: string,
        request: Apollo.PullVersionRequest = {},
        requestOptions?: AgentVersions.RequestOptions,
    ): core.HttpResponsePromise<Apollo.AgentVersionPullResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pullVersion(agentId, versionId, request, requestOptions));
    }

    private async __pullVersion(
        agentId: string,
        versionId: string,
        request: Apollo.PullVersionRequest = {},
        requestOptions?: AgentVersions.RequestOptions,
    ): Promise<core.WithRawResponse<Apollo.AgentVersionPullResponse>> {
        const { version_tag: versionTag } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (versionTag != null) {
            _queryParams.version_tag = versionTag;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    ((await core.Supplier.get(this._options.environment)) ?? environments.ApolloEnvironment.Gcp).base,
                `management/v1/agents/${core.url.encodePathParam(agentId)}/versions/${core.url.encodePathParam(versionId)}/pull`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Apollo.AgentVersionPullResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Apollo.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Apollo.UnauthorizedError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Apollo.ForbiddenError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Apollo.NotFoundError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 409:
                    throw new Apollo.ConflictError(_response.error.body as Apollo.ErrorResponse, _response.rawResponse);
                case 422:
                    throw new Apollo.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Apollo.InternalServerError(
                        _response.error.body as Apollo.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ApolloError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ApolloError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ApolloTimeoutError(
                    "Timeout exceeded when calling GET /management/v1/agents/{agentId}/versions/{versionId}/pull.",
                );
            case "unknown":
                throw new errors.ApolloError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
