// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "phone_number",
 *         agent_id: "agent_id"
 *     }
 */
export interface InitiateThreadRequest {
    /** Recipient phone number in E.164 (e.g. +14155551234). */
    phone_number: string;
    /** Agent the thread targets. */
    agent_id: string;
    /** When set, continue this thread instead of creating a new one. */
    thread_id?: string;
    /** User ref id for a new thread; defaults to the phone's digits. */
    user_ref_id?: string;
    /** Opener body for non-template channels (SMS). Ignored by WhatsApp (uses templates). */
    text?: string;
    /** WhatsApp only: Twilio Content template SID override. */
    template_id?: string;
    /** WhatsApp only: bound to template variable {{1}}. */
    agent_display_name?: string;
    /** WhatsApp only: additional template variable overrides ({{2}}, {{3}}, …). */
    content_variables?: Record<string, string | undefined>;
}
