// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "phone_number"
 *     }
 */
export interface InitiateThreadRequest {
    /** Recipient phone number in E.164 (e.g. +14155551234). */
    phone_number: string;
    /** When set, continue this thread instead of creating a new one. */
    thread_id?: string;
    /** User id for a new thread; defaults to the phone's digits. */
    user_id?: string;
    /** Opener body for non-template channels (SMS). Ignored by WhatsApp (uses templates). */
    text?: string;
    /** WhatsApp only: bound to template variable {{1}}. */
    agent_display_name?: string;
}
