// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentVersions", () => {
    test("list_versions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            results: [
                {
                    id: "id",
                    agent_id: "agent_id",
                    version_number: 1,
                    version_revision_number: 1,
                    version_tag: "version_tag",
                    status: "draft",
                    parent_version_id: "parent_version_id",
                    label: "label",
                    tags: ["tags", "tags"],
                    notes: "notes",
                    stats: {
                        workflows: 1,
                        policies: 1,
                        agent_placeholders: 1,
                        scope_entities: 1,
                        integrations: 1,
                        card_templates: 1,
                        parameters: 1,
                        knowledge_bases: 1,
                        agent_properties: 1,
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    published_at: "2024-01-15T09:30:00Z",
                },
                {
                    id: "id",
                    agent_id: "agent_id",
                    version_number: 1,
                    version_revision_number: 1,
                    version_tag: "version_tag",
                    status: "draft",
                    parent_version_id: "parent_version_id",
                    label: "label",
                    tags: ["tags", "tags"],
                    notes: "notes",
                    stats: {
                        workflows: 1,
                        policies: 1,
                        agent_placeholders: 1,
                        scope_entities: 1,
                        integrations: 1,
                        card_templates: 1,
                        parameters: 1,
                        knowledge_bases: 1,
                        agent_properties: 1,
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    published_at: "2024-01-15T09:30:00Z",
                },
            ],
            meta: { has_more: true, after_cursor: "after_cursor", before_cursor: "before_cursor" },
            links: { next: "next", prev: "prev" },
        };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.listVersions("agentId", {
            filters: {},
        });
        expect(response).toEqual({
            results: [
                {
                    id: "id",
                    agent_id: "agent_id",
                    version_number: 1,
                    version_revision_number: 1,
                    version_tag: "version_tag",
                    status: "draft",
                    parent_version_id: "parent_version_id",
                    label: "label",
                    tags: ["tags", "tags"],
                    notes: "notes",
                    stats: {
                        workflows: 1,
                        policies: 1,
                        agent_placeholders: 1,
                        scope_entities: 1,
                        integrations: 1,
                        card_templates: 1,
                        parameters: 1,
                        knowledge_bases: 1,
                        agent_properties: 1,
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    published_at: "2024-01-15T09:30:00Z",
                },
                {
                    id: "id",
                    agent_id: "agent_id",
                    version_number: 1,
                    version_revision_number: 1,
                    version_tag: "version_tag",
                    status: "draft",
                    parent_version_id: "parent_version_id",
                    label: "label",
                    tags: ["tags", "tags"],
                    notes: "notes",
                    stats: {
                        workflows: 1,
                        policies: 1,
                        agent_placeholders: 1,
                        scope_entities: 1,
                        integrations: 1,
                        card_templates: 1,
                        parameters: 1,
                        knowledge_bases: 1,
                        agent_properties: 1,
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    published_at: "2024-01-15T09:30:00Z",
                },
            ],
            meta: {
                has_more: true,
                after_cursor: "after_cursor",
                before_cursor: "before_cursor",
            },
            links: {
                next: "next",
                prev: "prev",
            },
        });
    });

    test("list_versions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("list_versions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("list_versions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("list_versions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("list_versions (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("list_versions (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("list_versions (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.listVersions("agentId", {
                filters: {},
            });
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("create_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = {
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.createVersion("agentId", {
            source: "version",
        });
        expect(response).toEqual({
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        });
    });

    test("create_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("create_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("create_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("create_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("create_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("create_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("create_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { source: "version" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.createVersion("agentId", {
                source: "version",
            });
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("update_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.updateVersion("agentId", "versionId");
        expect(response).toEqual({
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        });
    });

    test("update_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("update_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("update_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("update_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("update_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("update_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("update_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .patch("/management/v1/agents/agentId/versions/versionId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.updateVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("publish_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.publishVersion("agentId", "versionId");
        expect(response).toEqual({
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        });
    });

    test("publish_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("publish_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("publish_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("publish_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("publish_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("publish_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("publish_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/publish")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.publishVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("archive_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.archiveVersion("agentId", "versionId");
        expect(response).toEqual({
            id: "id",
            agent_id: "agent_id",
            version_number: 1,
            version_revision_number: 1,
            version_tag: "version_tag",
            status: "draft",
            parent_version_id: "parent_version_id",
            label: "label",
            tags: ["tags"],
            notes: "notes",
            stats: {
                workflows: 1,
                policies: 1,
                agent_placeholders: 1,
                scope_entities: 1,
                integrations: 1,
                card_templates: 1,
                parameters: 1,
                knowledge_bases: 1,
                agent_properties: 1,
            },
            created_at: "2024-01-15T09:30:00Z",
            published_at: "2024-01-15T09:30:00Z",
        });
    });

    test("archive_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("archive_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("archive_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("archive_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("archive_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("archive_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("archive_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/archive")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.archiveVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("push_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { key: "value" } };
        const rawResponseBody = {
            agent_id: "agent_id",
            version_id: "version_id",
            new_version_revision_number: 1,
            new_version_tag: "new_version_tag",
            revision_id: "revision_id",
            sha256: "sha256",
            size: 1,
            created_at: "2024-01-15T09:30:00Z",
            commit_message: "commit_message",
        };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.pushVersion("agentId", "versionId", {
            caller: "agent_builder",
            bundle: {
                key: "value",
            },
        });
        expect(response).toEqual({
            agent_id: "agent_id",
            version_id: "version_id",
            new_version_revision_number: 1,
            new_version_tag: "new_version_tag",
            revision_id: "revision_id",
            sha256: "sha256",
            size: 1,
            created_at: "2024-01-15T09:30:00Z",
            commit_message: "commit_message",
        });
    });

    test("push_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("push_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("push_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("push_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("push_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("push_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("push_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { caller: "agent_builder", bundle: { bundle: { key: "value" } } };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/agents/agentId/versions/versionId/push")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pushVersion("agentId", "versionId", {
                caller: "agent_builder",
                bundle: {
                    bundle: {
                        key: "value",
                    },
                },
            });
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("pull_version (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            return_type: "return_type",
            agent_id: "agent_id",
            version_id: "version_id",
            version_tag: "version_tag",
            bundle: { key: "value" },
            expires_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentVersions.pullVersion("agentId", "versionId", {
            version_tag: "version_tag",
        });
        expect(response).toEqual({
            return_type: "return_type",
            agent_id: "agent_id",
            version_id: "version_id",
            version_tag: "version_tag",
            bundle: {
                key: "value",
            },
            expires_at: "2024-01-15T09:30:00Z",
        });
    });

    test("pull_version (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("pull_version (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("pull_version (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("pull_version (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("pull_version (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("pull_version (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("pull_version (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/agents/agentId/versions/versionId/pull")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentVersions.pullVersion("agentId", "versionId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });
});
