// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ControllerApi", () => {
    test("list_user_tasks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {
            tasks: [
                {
                    id: "id",
                    user_id: "user_id",
                    title: "title",
                    welcome_message: "welcome_message",
                    followup_suggestions: ["followup_suggestions"],
                },
            ],
            total: 1,
            page: 1,
            size: 1,
        };
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.listUserTasks({
            user_id: "user_id",
            page: 1,
            size: 1,
        });
        expect(response).toEqual({
            tasks: [
                {
                    id: "id",
                    user_id: "user_id",
                    title: "title",
                    welcome_message: "welcome_message",
                    followup_suggestions: ["followup_suggestions"],
                },
            ],
            total: 1,
            page: 1,
            size: 1,
        });
    });

    test("list_user_tasks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.listUserTasks({
                user_id: "user_id",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("create_task (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });
        const rawRequestBody = { user_id: "user_id", task_origin_type: "stores" };
        const rawResponseBody = {
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .post("/api/v1/external/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.createTask({
            user_id: "user_id",
            task_origin_type: "stores",
        });
        expect(response).toEqual({
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("create_task (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });
        const rawRequestBody = { user_id: "user_id", task_origin_type: "stores" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/api/v1/external/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.createTask({
                user_id: "user_id",
                task_origin_type: "stores",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_task_messages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: { id: "id", type: "user", email: "email" },
                receiver: { id: "id", type: "user", email: "email" },
                cards: [{ id: "id", name: "name", category: "category", parameters: [], is_recommended: true }],
                welcome_message: "welcome_message",
                followup_suggestions: ["followup_suggestions"],
                executed_workflows: ["executed_workflows"],
                url: "url",
            },
        ];
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks/task_id/messages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTaskMessages("task_id");
        expect(response).toEqual([
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: {
                    id: "id",
                    type: "user",
                    email: "email",
                },
                receiver: {
                    id: "id",
                    type: "user",
                    email: "email",
                },
                cards: [
                    {
                        id: "id",
                        name: "name",
                        category: "category",
                        parameters: [],
                        is_recommended: true,
                    },
                ],
                welcome_message: "welcome_message",
                followup_suggestions: ["followup_suggestions"],
                executed_workflows: ["executed_workflows"],
                url: "url",
            },
        ]);
    });

    test("get_task_messages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks/task_id/messages")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTaskMessages("task_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("send_message (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id", text: "text" };
        const rawResponseBody = {
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: { id: "id", type: "user", email: "email" },
            receiver: { id: "id", type: "user", email: "email" },
            cards: [
                {
                    id: "id",
                    name: "name",
                    category: "category",
                    query: { key: "value" },
                    parameters: [],
                    sub_entities: [{ name: "name", items: [{ parameters: [{ param: "param", title: "title" }] }] }],
                    self_review: { score: { label: "HIGH", method: "INVENTORY_CLASSIFICATION" }, type: "WORKFLOW" },
                    is_recommended: true,
                },
            ],
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
            executed_workflows: ["executed_workflows"],
            url: "url",
        };
        server
            .mockEndpoint()
            .post("/api/v1/external/message")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.sendMessage({
            is_external_api: true,
            task_id: "task_id",
            text: "text",
        });
        expect(response).toEqual({
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: {
                id: "id",
                type: "user",
                email: "email",
            },
            receiver: {
                id: "id",
                type: "user",
                email: "email",
            },
            cards: [
                {
                    id: "id",
                    name: "name",
                    category: "category",
                    query: {
                        key: "value",
                    },
                    parameters: [],
                    sub_entities: [
                        {
                            name: "name",
                            items: [
                                {
                                    parameters: [
                                        {
                                            param: "param",
                                            title: "title",
                                        },
                                    ],
                                },
                            ],
                        },
                    ],
                    self_review: {
                        score: {
                            label: "HIGH",
                            method: "INVENTORY_CLASSIFICATION",
                        },
                        type: "WORKFLOW",
                    },
                    is_recommended: true,
                },
            ],
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
            executed_workflows: ["executed_workflows"],
            url: "url",
        });
    });

    test("send_message (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id", text: "text" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/api/v1/external/message")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.sendMessage({
                task_id: "task_id",
                text: "text",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_product_metadata (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/external/product-metadata")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getProductMetadata({
            link: "link",
        });
        expect(response).toEqual({
            key: "value",
        });
    });

    test("get_product_metadata (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/product-metadata")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getProductMetadata({
                link: "link",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_workflows_metadata (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {
            workflows: [
                {
                    id: "id",
                    name: "name",
                    metadata: { key: "value" },
                    produce_options: true,
                    is_internal_context: true,
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/api/v1/external/workflows/metadata")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getWorkflowsMetadata();
        expect(response).toEqual({
            workflows: [
                {
                    id: "id",
                    name: "name",
                    metadata: {
                        key: "value",
                    },
                    produce_options: true,
                    is_internal_context: true,
                },
            ],
        });
    });

    test("get_workflows_metadata (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            networkApiKey: "test",
            environment: { base: server.baseUrl, gcp: server.baseUrl, azure: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/workflows/metadata")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getWorkflowsMetadata();
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });
});
