// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ControllerApi", () => {
    test("list_user_tasks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });

        const rawResponseBody = {
            tasks: [
                {
                    id: "id",
                    user_id: "user_id",
                    title: "title",
                    welcome_message: "welcome_message",
                    followup_suggestions: ["followup_suggestions"],
                },
            ],
            total: 1,
            page: 1,
            size: 1,
        };
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.listUserTasks({
            user_id: "user_id",
            page: 1,
            size: 1,
        });
        expect(response).toEqual({
            tasks: [
                {
                    id: "id",
                    user_id: "user_id",
                    title: "title",
                    welcome_message: "welcome_message",
                    followup_suggestions: ["followup_suggestions"],
                },
            ],
            total: 1,
            page: 1,
            size: 1,
        });
    });

    test("list_user_tasks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.listUserTasks({
                user_id: "user_id",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("create_task (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .post("/api/v1/external/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.createTask({
            user_id: "user_id",
        });
        expect(response).toEqual({
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("create_task (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });
        const rawRequestBody = { user_id: "user_id" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/api/v1/external/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.createTask({
                user_id: "user_id",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_task_messages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: { id: "id", type: "user", email: "email" },
                receiver: { id: "id", type: "user", email: "email" },
                cards: [{ id: "id", name: "name", parameters: [], is_recommended: true }],
                followup_suggestions: ["followup_suggestions"],
            },
        ];
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks/task_id/messages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.getTaskMessages("task_id");
        expect(response).toEqual([
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: {
                    id: "id",
                    type: "user",
                    email: "email",
                },
                receiver: {
                    id: "id",
                    type: "user",
                    email: "email",
                },
                cards: [
                    {
                        id: "id",
                        name: "name",
                        parameters: [],
                        is_recommended: true,
                    },
                ],
                followup_suggestions: ["followup_suggestions"],
            },
        ]);
    });

    test("get_task_messages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/api/v1/external/tasks/task_id/messages")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.getTaskMessages("task_id");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("send_message (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id", text: "text" };
        const rawResponseBody = {
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: { id: "id", type: "user", email: "email" },
            receiver: { id: "id", type: "user", email: "email" },
            cards: [{ id: "id", name: "name", parameters: [], is_recommended: true }],
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .post("/api/v1/external/message")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.controllerApi.sendMessage({
            is_external_api: true,
            task_id: "task_id",
            text: "text",
        });
        expect(response).toEqual({
            id: "id",
            created_at: "created_at",
            text: "text",
            sender: {
                id: "id",
                type: "user",
                email: "email",
            },
            receiver: {
                id: "id",
                type: "user",
                email: "email",
            },
            cards: [
                {
                    id: "id",
                    name: "name",
                    parameters: [],
                    is_recommended: true,
                },
            ],
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("send_message (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            apiKey: "test",
            networkApiKey: "test",
            environment: { base: server.baseUrl, staging: server.baseUrl },
        });
        const rawRequestBody = { task_id: "task_id", text: "text" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/api/v1/external/message")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.controllerApi.sendMessage({
                task_id: "task_id",
                text: "text",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });
});
