// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Projects", () => {
    test("list_projects (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            results: [
                { id: "id", name: "name", created_at: "2024-01-15T09:30:00Z", updated_at: "2024-01-15T09:30:00Z" },
            ],
            meta: { has_more: true, after_cursor: "after_cursor", before_cursor: "before_cursor" },
            links: { next: "next", prev: "prev" },
        };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.listProjects({
            "page[size]": 1,
            "page[after]": "page[after]",
            "page[before]": "page[before]",
            sort_by: "sort_by",
            sort_order: "asc",
        });
        expect(response).toEqual({
            results: [
                {
                    id: "id",
                    name: "name",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            meta: {
                has_more: true,
                after_cursor: "after_cursor",
                before_cursor: "before_cursor",
            },
            links: {
                next: "next",
                prev: "prev",
            },
        });
    });

    test("list_projects (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("list_projects (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("list_projects (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("list_projects (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("list_projects (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("list_projects (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("list_projects (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("create_project (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            id: "id",
            name: "name",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.createProject({
            name: "name",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("create_project (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("create_project (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("create_project (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("create_project (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("create_project (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("create_project (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("create_project (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/management/v1/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "name",
            });
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_project (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            name: "name",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProject("projectId");
        expect(response).toEqual({
            id: "id",
            name: "name",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        });
    });

    test("get_project (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_project (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_project (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_project (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_project (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_project (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_project (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject("projectId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("delete_project (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        server.mockEndpoint().delete("/management/v1/projects/projectId").respondWith().statusCode(200).build();

        const response = await client.projects.deleteProject("projectId");
        expect(response).toEqual(undefined);
    });

    test("delete_project (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("delete_project (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("delete_project (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("delete_project (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("delete_project (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("delete_project (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("delete_project (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .delete("/management/v1/projects/projectId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject("projectId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_project_usage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            interaction_count: 1,
            input_tokens: 1,
            output_tokens: 1,
            cache_read_tokens: 1,
            reasoning_tokens: 1,
            total_tokens: 1,
        };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProjectUsage("projectId", {
            created_from: "2024-01-15T09:30:00Z",
            created_to: "2024-01-15T09:30:00Z",
        });
        expect(response).toEqual({
            interaction_count: 1,
            input_tokens: 1,
            output_tokens: 1,
            cache_read_tokens: 1,
            reasoning_tokens: 1,
            total_tokens: 1,
        });
    });

    test("get_project_usage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_project_usage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_project_usage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_project_usage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_project_usage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_project_usage (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_project_usage (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/projects/projectId/usage")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectUsage("projectId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });
});
