// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Threads", () => {
    test("list_threads (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            results: [
                { id: "id", title: "title", created_at: "created_at" },
                { id: "id", title: "title", created_at: "created_at" },
            ],
            meta: { has_more: true, after_cursor: "after_cursor", before_cursor: "before_cursor" },
            links: { next: "next", prev: "prev" },
        };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.listThreads({
            filters: {},
        });
        expect(response).toEqual({
            results: [
                {
                    id: "id",
                    title: "title",
                    created_at: "created_at",
                },
                {
                    id: "id",
                    title: "title",
                    created_at: "created_at",
                },
            ],
            meta: {
                has_more: true,
                after_cursor: "after_cursor",
                before_cursor: "before_cursor",
            },
            links: {
                next: "next",
                prev: "prev",
            },
        });
    });

    test("list_threads (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("list_threads (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("list_threads (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("list_threads (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("list_threads (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("list_threads (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("list_threads (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.listThreads({
                filters: {},
            });
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_thread (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.getThread("threadId");
        expect(response).toEqual({
            id: "id",
            user_id: "user_id",
            title: "title",
            welcome_message: "welcome_message",
            followup_suggestions: ["followup_suggestions"],
        });
    });

    test("get_thread (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_thread (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_thread (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_thread (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_thread (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_thread (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_thread (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThread("threadId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_thread_trace (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = [
            {
                input: { message: "message" },
                understanding: { intents: ["intents"], guardrails: { passed: null, reason: null } },
                decisions: [
                    {
                        type: null,
                        tool: null,
                        parent_tool: null,
                        track_id: null,
                        status: null,
                        check_status: null,
                        trigger: null,
                        trigger_type: null,
                        rule: null,
                        text: null,
                        fail_reason: null,
                        computation: null,
                        output_param: null,
                        output_title: null,
                        qualified: null,
                        matched_branch: null,
                    },
                ],
                computed_parameters: [{ code: null, title: null, scope: null }],
                response: {
                    type: "type",
                    message: "message",
                    suggestions: ["suggestions"],
                    question_reason: "question_reason",
                    asking_for: ["asking_for"],
                    block_message: "block_message",
                    error: "error",
                    jsx_widgets: [
                        { name: null, category: null, rendered_jsx: null, is_recommended: null, index: null },
                    ],
                },
                rules_evaluations: [{ code: null, triggered: null, reason: null }],
            },
        ];
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.getThreadTrace("threadId");
        expect(response).toEqual([
            {
                input: {
                    message: "message",
                },
                understanding: {
                    intents: ["intents"],
                    guardrails: {
                        passed: null,
                        reason: null,
                    },
                },
                decisions: [
                    {
                        type: null,
                        tool: null,
                        parent_tool: null,
                        track_id: null,
                        status: null,
                        check_status: null,
                        trigger: null,
                        trigger_type: null,
                        rule: null,
                        text: null,
                        fail_reason: null,
                        computation: null,
                        output_param: null,
                        output_title: null,
                        qualified: null,
                        matched_branch: null,
                    },
                ],
                computed_parameters: [
                    {
                        code: null,
                        title: null,
                        scope: null,
                    },
                ],
                response: {
                    type: "type",
                    message: "message",
                    suggestions: ["suggestions"],
                    question_reason: "question_reason",
                    asking_for: ["asking_for"],
                    block_message: "block_message",
                    error: "error",
                    jsx_widgets: [
                        {
                            name: null,
                            category: null,
                            rendered_jsx: null,
                            is_recommended: null,
                            index: null,
                        },
                    ],
                },
                rules_evaluations: [
                    {
                        code: null,
                        triggered: null,
                        reason: null,
                    },
                ],
            },
        ]);
    });

    test("get_thread_trace (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_thread_trace (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_thread_trace (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_thread_trace (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_thread_trace (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_thread_trace (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_thread_trace (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/trace")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadTrace("threadId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_interaction_trace (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = {
            input: { message: "message" },
            understanding: { intents: ["intents"], guardrails: { passed: true, reason: "reason" } },
            decisions: [
                {
                    type: "type",
                    tool: "tool",
                    parent_tool: "parent_tool",
                    track_id: "track_id",
                    status: "status",
                    check_status: "check_status",
                    trigger: { type: null, reasons: null, matched_objective: null },
                    trigger_type: "trigger_type",
                    rule: { type: null, action: null, reason: null, code: null },
                    text: "text",
                    fail_reason: "fail_reason",
                    computation: "computation",
                    output_param: "output_param",
                    output_title: "output_title",
                    qualified: true,
                    matched_branch: "matched_branch",
                },
            ],
            computed_parameters: [{ code: "code", title: "title", scope: "scope" }],
            response: {
                type: "type",
                message: "message",
                suggestions: ["suggestions"],
                question_reason: "question_reason",
                asking_for: ["asking_for"],
                block_message: "block_message",
                error: "error",
                jsx_widgets: [{ name: null, category: null, rendered_jsx: null, is_recommended: null, index: null }],
            },
            rules_evaluations: [
                { code: "code", triggered: true, reason: [{ passed: null, trigger_type: null, condition: null }] },
            ],
        };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.getInteractionTrace("interactionId");
        expect(response).toEqual({
            input: {
                message: "message",
            },
            understanding: {
                intents: ["intents"],
                guardrails: {
                    passed: true,
                    reason: "reason",
                },
            },
            decisions: [
                {
                    type: "type",
                    tool: "tool",
                    parent_tool: "parent_tool",
                    track_id: "track_id",
                    status: "status",
                    check_status: "check_status",
                    trigger: {
                        type: null,
                        reasons: null,
                        matched_objective: null,
                    },
                    trigger_type: "trigger_type",
                    rule: {
                        type: null,
                        action: null,
                        reason: null,
                        code: null,
                    },
                    text: "text",
                    fail_reason: "fail_reason",
                    computation: "computation",
                    output_param: "output_param",
                    output_title: "output_title",
                    qualified: true,
                    matched_branch: "matched_branch",
                },
            ],
            computed_parameters: [
                {
                    code: "code",
                    title: "title",
                    scope: "scope",
                },
            ],
            response: {
                type: "type",
                message: "message",
                suggestions: ["suggestions"],
                question_reason: "question_reason",
                asking_for: ["asking_for"],
                block_message: "block_message",
                error: "error",
                jsx_widgets: [
                    {
                        name: null,
                        category: null,
                        rendered_jsx: null,
                        is_recommended: null,
                        index: null,
                    },
                ],
            },
            rules_evaluations: [
                {
                    code: "code",
                    triggered: true,
                    reason: [
                        {
                            passed: null,
                            trigger_type: null,
                            condition: null,
                        },
                    ],
                },
            ],
        });
    });

    test("get_interaction_trace (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_interaction_trace (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_interaction_trace (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_interaction_trace (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_interaction_trace (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_interaction_trace (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_interaction_trace (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/interactions/interactionId/trace")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getInteractionTrace("interactionId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });

    test("get_thread_messages (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: { id: "id", type: "type" },
                receiver: { id: "id", type: "type" },
                cards: [{}],
                welcome_message: "welcome_message",
                followup_suggestions: ["followup_suggestions"],
                url: "url",
                input_tokens: 1,
                output_tokens: 1,
            },
        ];
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.threads.getThreadMessages("threadId");
        expect(response).toEqual([
            {
                id: "id",
                created_at: "created_at",
                text: "text",
                sender: {
                    id: "id",
                    type: "type",
                },
                receiver: {
                    id: "id",
                    type: "type",
                },
                cards: [{}],
                welcome_message: "welcome_message",
                followup_suggestions: ["followup_suggestions"],
                url: "url",
                input_tokens: 1,
                output_tokens: 1,
            },
        ]);
    });

    test("get_thread_messages (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("get_thread_messages (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("get_thread_messages (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("get_thread_messages (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("get_thread_messages (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("get_thread_messages (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("get_thread_messages (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            environment: { base: server.baseUrl, production: server.baseUrl, local: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .get("/management/v1/threads/threadId/messages")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.threads.getThreadMessages("threadId");
        }).rejects.toThrow(Apollo.InternalServerError);
    });
});
