// This file was auto-generated by Fern from our API Definition.

import * as Apollo from "../../src/api/index";
import { ApolloClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Webhooks", () => {
    test("receive_agent_event (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { event_id: "event_id" };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.receiveAgentEvent();
        expect(response).toEqual({
            event_id: "event_id",
        });
    });

    test("receive_agent_event (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.BadRequestError);
    });

    test("receive_agent_event (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.UnauthorizedError);
    });

    test("receive_agent_event (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.ForbiddenError);
    });

    test("receive_agent_event (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.NotFoundError);
    });

    test("receive_agent_event (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.ConflictError);
    });

    test("receive_agent_event (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.UnprocessableEntityError);
    });

    test("receive_agent_event (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new ApolloClient({
            token: "test",
            organizationApiKey: "test",
            environment: { base: server.baseUrl, production: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { error: { code: "code", message: "message" } };
        server
            .mockEndpoint()
            .post("/messaging/v1/events")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.receiveAgentEvent();
        }).rejects.toThrow(Apollo.InternalServerError);
    });
});
