// This file was auto-generated by Fern from our API Definition.

import { ApolloSession } from "./api/resources/apolloSession/client/Client.js";
import { ControllerApi } from "./api/resources/controllerApi/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace ApolloClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ApolloClient {
    protected readonly _options: ApolloClient.Options;
    protected _controllerApi: ControllerApi | undefined;
    protected _apolloSession: ApolloSession | undefined;

    constructor(_options: ApolloClient.Options = {}) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "x-network-api-key": _options?.networkApiKey,
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@aui.io/aui-client",
                    "X-Fern-SDK-Version": "1.1.11",
                    "User-Agent": "@aui.io/aui-client/1.1.11",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get controllerApi(): ControllerApi {
        return (this._controllerApi ??= new ControllerApi(this._options));
    }

    public get apolloSession(): ApolloSession {
        return (this._apolloSession ??= new ApolloSession(this._options));
    }
}
