// This file was auto-generated by Fern from our API Definition.

import { ExternalApis } from "./api/resources/externalApis/client/Client.js";
import { ExternalSession } from "./api/resources/externalSession/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace ApolloClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ApolloClient {
    protected readonly _options: ApolloClient.Options;
    protected _externalApis: ExternalApis | undefined;
    protected _externalSession: ExternalSession | undefined;

    constructor(_options: ApolloClient.Options = {}) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "x-network-api-key": _options?.networkApiKey,
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "@aui.io/apollo-sdk",
                    "X-Fern-SDK-Version": "1.1.1",
                    "User-Agent": "@aui.io/apollo-sdk/1.1.1",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get externalApis(): ExternalApis {
        return (this._externalApis ??= new ExternalApis(this._options));
    }

    public get externalSession(): ExternalSession {
        return (this._externalSession ??= new ExternalSession(this._options));
    }
}
