// This file was auto-generated by Fern from our API Definition.
// MANUALLY FIXED: Added wsUrl property for WebSocket URL resolution (see .fernignore)

export interface ApolloEnvironmentUrls {
    base: string;
    wsUrl: string;
}

export const ApolloEnvironment = {
    Gcp: {
        base: "https://api.aui.io/ia-controller",
        wsUrl: "wss://api.aui.io",
    },
    Azure: {
        base: "https://azure-v2.aui.io/ia-controller",
        wsUrl: "wss://azure-v2.aui.io",
    },
    // Default points to Gcp for backwards compatibility
    Default: {
        base: "https://api.aui.io/ia-controller",
        wsUrl: "wss://api.aui.io",
    },
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Default | typeof ApolloEnvironment.Gcp | typeof ApolloEnvironment.Azure;
