// This file was auto-generated by Fern from our API Definition.
// MANUALLY FIXED: Added GCP/AZURE environments with correct URLs (see .fernignore)

export interface ApolloEnvironmentUrls {
    base: string;
    wsUrl: string;
}

export const ApolloEnvironment = {
    GCP: {
        base: "https://api.aui.io/ia-controller",
        wsUrl: "wss://api.aui.io",
    },
    AZURE: {
        base: "https://azure-v2.aui.io/ia-controller",
        wsUrl: "wss://azure-v2.aui.io",
    },
    // Default points to GCP for backwards compatibility
    Default: {
        base: "https://api.aui.io/ia-controller",
        wsUrl: "wss://api.aui.io",
    },
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Default | typeof ApolloEnvironment.GCP | typeof ApolloEnvironment.AZURE;
