// This file was auto-generated by Fern from our API Definition.

export interface ApolloEnvironmentUrls {
    base: string;
    production: string;
}

export const ApolloEnvironment = {
    Gcp: {
        base: "https://api-v3.aui.io/apollo-api-v2",
        production: "wss://api-v3.aui.io/apollo-api-v2",
    },
} as const;

export type ApolloEnvironment = typeof ApolloEnvironment.Gcp;
