// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         user_id: "user_id",
 *         task_origin_type: "stores"
 *     }
 */
export interface CreateTaskRequest {
    user_id: string;
    task_origin_type: Apollo.RecordOriginType;
}
