// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface DirectFollowupSuggestionsRequest {
    context?: Record<string, unknown>;
    created_by?: string;
}
