// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface DirectFollowupSuggestionsRequest {
    context?: Record<string, unknown>;
    record_scope?: Apollo.RecordScope;
    created_by?: string;
}
