// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         include_business_logic: true,
 *         include_context_logic: true
 *     }
 */
export interface GetTraceInfoRequest {
    /** When false, omits NLU/understanding and business decisions (rules, tools, params, etc.); input and response stay populated. */
    include_business_logic?: boolean;
    /** When false, omits the context section and call_integration (REST/RAG/MCP) decisions. */
    include_context_logic?: boolean;
}
