// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         include_business_trace: true,
 *         include_context_trace: true,
 *         is_external_api: true,
 *         task_id: "task_id"
 *     }
 */
export interface SubmitMessageRequest {
    /** When true, includes NLU/understanding and business decisions (rules, tools, params, etc.) in trace_info. */
    include_business_trace?: boolean;
    /** When true, includes the context section and call_integration (REST/RAG/MCP) decisions in trace_info. */
    include_context_trace?: boolean;
    is_external_api?: boolean;
    task_id: string;
    text?: string;
    context?: Apollo.Context;
    agent_variables?: Record<string, unknown>;
    static_context?: Record<string, unknown>;
}
