// This file was auto-generated by Fern from our API Definition.

import type * as Apollo from "../../../../index.js";

/**
 * @example
 *     {
 *         include_trace_info: true,
 *         is_external_api: true,
 *         task_id: "task_id"
 *     }
 */
export interface SubmitMessageRequest {
    include_trace_info?: boolean;
    is_external_api?: boolean;
    task_id: string;
    text?: string;
    context?: Apollo.Context;
    agent_variables?: Record<string, unknown>;
    static_context?: Record<string, unknown>;
}
