// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phoneNumber: "phoneNumber",
 *         channel: "channel"
 *     }
 */
export interface TextConversationInitiateRequest {
    /** Phone number in E.164 format (e.g., +1234567890) */
    phoneNumber: string;
    /** Channel type: 'whatsapp' or 'sms' */
    channel: string;
    /** Optional initial message to send */
    message?: string;
}
