// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         source: "version"
 *     }
 */
export interface AgentVersionCreateRequest {
    source: AgentVersionCreateRequest.Source;
    /** Required when source='version' */
    from_version?: string;
    /** Required when source='template' */
    from_template?: string;
    label?: string;
    tags?: string[];
    notes?: string;
}

export namespace AgentVersionCreateRequest {
    export const Source = {
        Version: "version",
        AgentScope: "agent-scope",
        Template: "template",
        Empty: "empty",
    } as const;
    export type Source = (typeof Source)[keyof typeof Source];
}
