// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version_tag: "version_tag"
 *     }
 */
export interface PullVersionRequest {
    /** Revision tag (e.g. 'v3.2'). Omit for the version's current tag. */
    version_tag?: string;
}
